# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
   
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        test-type: [unit, lint]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
    - name: Run test (${{ matrix.test-type }})
      run: 'npm run test:${{ matrix.test-type }}'
      env:
        CI: true
